"""
core/tools/generators.py — Business content generators.

Generates structured outputs: markdown, HTML, JSON schema, PDF-ready text.
All follow BaseTool interface. Sandboxed to workspace.
"""
from __future__ import annotations

import json
import os
import time
import logging
from pathlib import Path

from core.tools.tool_template import BaseTool, ToolResult

log = logging.getLogger("jarvis.tools.generators")

_WORKSPACE = Path(os.getenv("WORKSPACE_DIR", "/app/workspace"))

def _safe_path(path_str: str) -> Path | None:
    try:
        target = (_WORKSPACE / path_str).resolve()
        if not str(target).startswith(str(_WORKSPACE.resolve())):
            return None
        return target
    except Exception:
        return None


class MarkdownGenerator(BaseTool):
    """Generate structured markdown documents."""
    name = "markdown_generate"
    risk_level = "LOW"
    description = "Generate markdown documents from structured input"
    timeout_seconds = 5.0

    def execute(self, title: str = "", sections: list = None,
                output_path: str = "", **kw) -> ToolResult:
        if not title:
            return ToolResult(ok=False, error="missing_title")
        sections = sections or []

        lines = [f"# {title}", ""]
        for sec in sections:
            if isinstance(sec, dict):
                heading = sec.get("heading", "Section")
                content = sec.get("content", "")
                level = sec.get("level", 2)
                lines.append(f"{'#' * level} {heading}")
                lines.append("")
                lines.append(content)
                lines.append("")
            elif isinstance(sec, str):
                lines.append(sec)
                lines.append("")

        md = "\n".join(lines)

        if output_path:
            safe = _safe_path(output_path)
            if safe is None:
                return ToolResult(ok=False, error="path_escape: must stay within workspace")
            safe.parent.mkdir(parents=True, exist_ok=True)
            safe.write_text(md, encoding="utf-8")
            return ToolResult(ok=True, result=f"Wrote {len(md)} chars to {output_path}")

        return ToolResult(ok=True, result=md)


class HtmlGenerator(BaseTool):
    """Generate simple HTML pages from structured input."""
    name = "html_generate"
    risk_level = "LOW"
    description = "Generate HTML pages from structured input"
    timeout_seconds = 5.0

    def execute(self, title: str = "", body_sections: list = None,
                css: str = "", output_path: str = "", **kw) -> ToolResult:
        if not title:
            return ToolResult(ok=False, error="missing_title")
        body_sections = body_sections or []

        default_css = """
        body { font-family: system-ui, sans-serif; max-width: 800px; margin: 0 auto; padding: 2rem; line-height: 1.6; color: #333; }
        h1 { color: #1a1a2e; border-bottom: 2px solid #e94560; padding-bottom: 0.5rem; }
        h2 { color: #16213e; }
        .section { margin: 1.5rem 0; }
        .cta { background: #e94560; color: white; padding: 12px 24px; border: none; border-radius: 6px; font-size: 1rem; cursor: pointer; text-decoration: none; display: inline-block; }
        .cta:hover { background: #c73e54; }
        footer { margin-top: 3rem; padding-top: 1rem; border-top: 1px solid #ddd; color: #888; font-size: 0.9rem; }
        """

        body_html = ""
        for sec in body_sections:
            if isinstance(sec, dict):
                tag = sec.get("tag", "div")
                content = sec.get("content", "")
                cls = sec.get("class", "section")
                body_html += f'<{tag} class="{cls}">{content}</{tag}>\n'
            elif isinstance(sec, str):
                body_html += f"<div class='section'>{sec}</div>\n"

        html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{title}</title>
    <style>{css or default_css}</style>
</head>
<body>
    <h1>{title}</h1>
    {body_html}
    <footer>Generated by JarvisMax</footer>
</body>
</html>"""

        if output_path:
            safe = _safe_path(output_path)
            if safe is None:
                return ToolResult(ok=False, error="path_escape: must stay within workspace")
            safe.parent.mkdir(parents=True, exist_ok=True)
            safe.write_text(html, encoding="utf-8")
            return ToolResult(ok=True, result=f"Wrote {len(html)} chars to {output_path}")

        return ToolResult(ok=True, result=html)


class JsonSchemaGenerator(BaseTool):
    """Generate JSON Schema from field definitions."""
    name = "json_schema_generate"
    risk_level = "LOW"
    description = "Generate JSON Schema documents from field definitions"
    timeout_seconds = 5.0

    def execute(self, schema_name: str = "", fields: list = None,
                required_fields: list = None, output_path: str = "", **kw) -> ToolResult:
        if not schema_name:
            return ToolResult(ok=False, error="missing_schema_name")
        fields = fields or []
        required_fields = required_fields or []

        properties = {}
        for f in fields:
            if isinstance(f, dict):
                name = f.get("name", "")
                ftype = f.get("type", "string")
                desc = f.get("description", "")
                if name:
                    prop = {"type": ftype}
                    if desc:
                        prop["description"] = desc
                    if "enum" in f:
                        prop["enum"] = f["enum"]
                    if "default" in f:
                        prop["default"] = f["default"]
                    properties[name] = prop

        schema = {
            "$schema": "https://json-schema.org/draft/2020-12/schema",
            "title": schema_name,
            "type": "object",
            "properties": properties,
            "required": required_fields or [f["name"] for f in fields if isinstance(f, dict) and f.get("required")],
            "additionalProperties": False,
        }

        result_json = json.dumps(schema, indent=2)

        if output_path:
            safe = _safe_path(output_path)
            if safe is None:
                return ToolResult(ok=False, error="path_escape: must stay within workspace")
            safe.parent.mkdir(parents=True, exist_ok=True)
            safe.write_text(result_json, encoding="utf-8")
            return ToolResult(ok=True, result=f"Wrote schema to {output_path}")

        return ToolResult(ok=True, result=result_json)


class HttpTestTool(BaseTool):
    """Test HTTP endpoints — check status, response time, content."""
    name = "http_test"
    risk_level = "LOW"
    description = "Test HTTP endpoints for health, status, and content"
    timeout_seconds = 10.0

    def execute(self, url: str = "", expected_status: int = 200,
                expected_content: str = "", **kw) -> ToolResult:
        if not url:
            return ToolResult(ok=False, error="missing_url")
        if not url.startswith(("http://", "https://")):
            return ToolResult(ok=False, error="invalid_url: must start with http(s)://")

        try:
            import requests
            start = time.time()
            resp = requests.get(url, timeout=self.timeout_seconds,
                                headers={"User-Agent": "JarvisMax/1.0"})
            elapsed_ms = (time.time() - start) * 1000

            checks = {
                "url": url,
                "status_code": resp.status_code,
                "response_time_ms": round(elapsed_ms, 1),
                "content_length": len(resp.text),
                "status_ok": resp.status_code == expected_status,
            }

            if expected_content:
                checks["content_found"] = expected_content in resp.text
            else:
                checks["content_found"] = True

            all_ok = checks["status_ok"] and checks["content_found"]
            checks["verdict"] = "PASS" if all_ok else "FAIL"

            return ToolResult(
                ok=all_ok,
                result=json.dumps(checks, indent=2),
                error="" if all_ok else f"expected {expected_status}, got {resp.status_code}",
            )

        except requests.Timeout:
            return ToolResult(ok=False, error="timeout", retryable=True)
        except requests.ConnectionError as e:
            return ToolResult(ok=False, error=f"connection_error: {str(e)[:200]}", retryable=True)
        except Exception as e:
            return ToolResult(ok=False, error=f"test_error: {str(e)[:200]}")
